"""initial backend schema

Revision ID: aa240d92facf
Revises:
Create Date: 2026-09-26 15:41:22.426683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa240d92facf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('video_key', sa.String(length=300), nullable=True),
    sa.Column('upload_expires_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drives_owner'), 'drives', ['owner'], unique=False)
    op.create_table('hazards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drive_id', sa.String(length=36), nullable=False),
    sa.Column('event_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=True),
    sa.Column('severity_basis', sa.String(length=200), nullable=True),
    sa.Column('video_offset_ms', sa.Integer(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('review_state', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'event_index')
    )
    op.create_index(op.f('ix_hazards_drive_id'), 'hazards', ['drive_id'], unique=False)
    op.create_index('ix_hazards_drive_offset', 'hazards', ['drive_id', 'video_offset_ms'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drive_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.String(length=40), nullable=True),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id')
    )
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drive_id', sa.String(length=36), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('horizontal_accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'offset_ms')
    )
    op.create_index(op.f('ix_locations_drive_id'), 'locations', ['drive_id'], unique=False)
    op.create_index('ix_locations_drive_offset', 'locations', ['drive_id', 'offset_ms'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hazard_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hazard_id')
    )
    op.create_table('report_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hazard_id', sa.String(length=36), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('submission_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hazard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_drafts')
    op.drop_table('evidence')
    op.drop_index('ix_locations_drive_offset', table_name='locations')
    op.drop_index(op.f('ix_locations_drive_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_hazards_drive_offset', table_name='hazards')
    op.drop_index(op.f('ix_hazards_drive_id'), table_name='hazards')
    op.drop_table('hazards')
    op.drop_index(op.f('ix_drives_owner'), table_name='drives')
    op.drop_table('drives')
    # ### end Alembic commands ###
